#连接mysql数据库
spring:
  datasource:
    username: ruangong
    password: root
    url: jdbc:mysql://39.97.252.94:3306/ruangong
    driver-class-name: com.mysql.jdbc.Driver


##整合mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

