#mysql
spring:
  datasource:
    username: ruangong
    password: root
    url: jdbc:mysql://39.97.252.94:3306/ruangong
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

##mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  ##push
push:
  appkey: e642cd56a37c2d5777bbc664
  secret: 802ee1a8dd3fd21cb34f62f5





